name: EKS Full Cleanup via Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  Plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::136770599741:role/github-action-role
          role-session-name: samplerolesession
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5
      - name: Terraform Init
        run: |
          cd module
          terraform init
      - name: Terraform plan
        run: |
          cd module
          terraform plan -out=tfplan
  apply:
    needs: Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::136770599741:role/github-action-role
          role-session-name: samplerolesession
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5
      - name: Terraform Apply
        run: |
          cd module
          terraform init
          terraform apply -auto-approve
