name: EKS Full Cleanup via Pipeline

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  Plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::000087384605:role/githubworkflowrole
          role-session-name: samplerolesession
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.6
      - name: Terraform Init
        working-directory: ./EKS-infrastructure
        run: terraform init
      - name: Terraform plan
        working-directory: ./EKS-infrastructure
        run: terraform plan -out=tfplan
  apply:
    needs: Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::000087384605:role/githubworkflowrole
          role-session-name: samplerolesession
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.6
      - name: Terraform Apply
        working-directory: ./EKS-infrastructure
        run: terraform apply -auto-approve tfplan